[package]
name = "roulette"
version = "0.1.0"
authors = ["Malik Shamsutdinov <malik.shamsutdinov@piano.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"